//! The same description, rendered for a person.
//!
//! Generated from the same model as the JSON rather than written beside it: a
//! prose reference that drifts from the machine-readable one is worse than no
//! prose reference, because a reader has no way to tell which of the two lied.

use std::fmt::Write as _;

use crate::decay::{DecayApi, Namespace, Symbol};

/// Renders the Decay surface as Markdown.
pub(crate) fn render(api: &DecayApi) -> String {
    let mut page = String::new();

    page.push_str(&preamble());
    page.push_str(
        "## `this`\n\nWhat the entity a script runs on offers, beyond the script's own fields.\n\n",
    );
    push_symbols(&mut page, &api.this);

    page.push_str("\n## Globals\n\nNames in scope without qualification. Decay has no imports, so each of these is a name a script cannot use for its own.\n\n");
    push_symbols(&mut page, &api.globals);

    page.push_str(&vectors());
    page.push_str(&timers());

    page.push_str("\n## Types\n");
    for namespace in &api.types {
        push_namespace(&mut page, namespace);
    }

    page
}

/// What a `Vec2` and a `Vec3` offer. They are the language's own values rather
/// than the host's, so this is read from the language's list, not the surface.
fn vectors() -> String {
    use decay_semantic::{COMPONENTS, Type, VectorOp};

    let mut section = String::from(
        "\n## Vectors\n\n`Vec2(x, y)` and `Vec3(x, y, z)` build one. Vectors add to and \
         subtract from vectors of their own size, scale by a number (`v * 2.0`, `2.0 * v`, \
         `v / 2.0`), negate, and compare with `==`. A component is read and assigned by name: \
         `v.x`, `v.y += 1.0`.\n\n",
    );
    for ty in [Type::Vec2, Type::Vec3] {
        let name = ty.display_name();
        let dimensions = ty.dimensions().unwrap_or(0);
        let _ = writeln!(section, "### `{name}`\n");
        for component in &COMPONENTS[..dimensions] {
            let _ = writeln!(section, "- `{component}`: `f32`");
        }
        for (op, spelled, _) in VectorOp::ALL {
            let line = match op {
                VectorOp::Length => format!("- `{spelled}`: `f32`"),
                VectorOp::Normalized => format!("- `{spelled}`: `{name}`"),
                VectorOp::Dot | VectorOp::Distance => format!("- `{spelled}({name})` → `f32`"),
                VectorOp::Lerp => format!("- `{spelled}({name}, f32)` → `{name}`"),
            };
            let _ = writeln!(section, "{line}");
        }
        section.push('\n');
    }
    section.truncate(section.trim_end().len());
    section.push('\n');
    section
}

/// What a `Timer` offers: like a vector, the language's own value, read from
/// the language's list.
fn timers() -> String {
    use decay_semantic::TimerProperty;

    let mut section = String::from(
        "\n## Timers\n\n`Timer(seconds)` starts one. A timer held in a script's field runs down \
         by each frame before that script's `update`; one held in a local does not. It is read, \
         never written into: start a new one to restart it.\n\n### `Timer`\n\n",
    );
    for (property, spelled) in TimerProperty::ALL {
        let ty = match property {
            TimerProperty::Done => "bool",
            TimerProperty::Left | TimerProperty::Duration | TimerProperty::Progress => "f32",
        };
        let _ = writeln!(section, "- `{spelled}`: `{ty}`");
    }
    section
}

fn preamble() -> String {
    format!(
        "# Decay host API\n\n\
         <!-- Generated by `{command}`. Do not edit by hand: a test fails when\n\
         this file disagrees with the host surface in `sindri-decay`. -->\n\n\
         Every namespace, call, and member a Decay script may name in this build\n\
         of the engine, derived from the one description the analyzer\n\
         type-checks against and the runtime host answers.\n\n\
         Each entry says what it is for; the reasons behind the design are in\n\
         [`docs/scripting.md`](../scripting.md).\n\n\
         The machine-readable form of this page is\n\
         [`decay-api.json`](decay-api.json).\n\n",
        command = crate::REGENERATE_COMMAND,
    )
}

fn push_namespace(page: &mut String, namespace: &Namespace) {
    let _ = write!(page, "\n### `{}`\n\n", namespace.name);
    if let Some(description) = namespace.description {
        let _ = write!(page, "{description}\n\n");
    }
    if namespace.members.is_empty() {
        page.push_str("The host names this type but has not described its members.\n");
        return;
    }
    push_symbols(page, &namespace.members);
}

fn push_symbols(page: &mut String, symbols: &[Symbol]) {
    if symbols.is_empty() {
        page.push_str("Nothing.\n");
        return;
    }
    for symbol in symbols {
        match symbol.reference() {
            Some(entry) => {
                let _ = writeln!(page, "- {} — {}", signature(symbol), entry.text);
            }
            None => {
                let _ = writeln!(page, "- {}", signature(symbol));
            }
        }
    }
}

/// One entry, written the way it would be read in a script.
fn signature(symbol: &Symbol) -> String {
    match symbol {
        Symbol::Value {
            name,
            type_name,
            read_only,
            ..
        } => format!(
            "`{name}`: `{type_name}`{}",
            if *read_only { " (read-only)" } else { "" }
        ),
        Symbol::Function {
            name,
            params,
            returns,
            reference,
        } => {
            let names = reference.map_or(&[][..], |entry| entry.params);
            let params: Vec<String> = params
                .iter()
                .enumerate()
                .map(|(index, ty)| match names.get(index) {
                    Some(name) => format!("{name}: {ty}"),
                    None => ty.clone(),
                })
                .collect();
            format!("`{name}({})` → `{returns}`", params.join(", "))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{render, signature};
    use crate::decay::{Symbol, describe};

    #[test]
    fn a_call_reads_as_a_signature() {
        let symbol = Symbol::Function {
            name: "axis".to_owned(),
            params: vec!["String".to_owned(), "String".to_owned()],
            returns: "f32".to_owned(),
            reference: None,
        };
        assert_eq!(signature(&symbol), "`axis(String, String)` → `f32`");
        let named = Symbol::Function {
            name: "axis".to_owned(),
            params: vec!["String".to_owned(), "String".to_owned()],
            returns: "f32".to_owned(),
            reference: sindri_decay::reference::member_entry("Input", "axis").copied(),
        };
        assert_eq!(
            signature(&named),
            "`axis(negative: String, positive: String)` → `f32`"
        );
    }

    #[test]
    fn the_page_names_every_type_the_description_carries() {
        let api = describe();
        let page = render(&api);
        for namespace in &api.types {
            assert!(
                page.contains(&format!("### `{}`", namespace.name)),
                "{} has a section",
                namespace.name
            );
        }
    }
}
